#!/usr/bin/env bash

# This script displays "Best School" 10 times using a while loop

# Initialize counter
counter=0

# Loop while counter is less than 10
while [ "$counter" -lt 10 ]; do
    echo "Best School"
    ((counter++))
done
