#!/usr/bin/env bash

# This script displays different messages based on specific numbers in the loop

# Initialize counter
counter=1

# Loop while counter is less than or equal to 20
while [ "$counter" -le 20 ]; do
    # Use case statement to check specific numbers
    case $counter in
        4)
            echo "$counter"
            echo "bad luck from China"
            ;;
        9)
            echo "$counter"
            echo "bad luck from Japan"
            ;;
        17)
            echo "$counter"
            echo "bad luck from Italy"
            ;;
        *)
            echo "$counter"
            ;;
    esac

    ((counter++))
done
