#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes

# Initialize variables
hour=0

# Loop for 12 hours
while [ "$hour" -le 12 ]; do
    echo "Hour: $hour"
    
    # Loop for 59 minutes
    minute=1
    while [ "$minute" -le 59 ]; do
        echo "$minute"
        ((minute++))
    done

    ((hour++))
done
